### ISSUE TITLE
Sending messages doesn't work in Android

### ISSUE THREAD

**Issue by jamesdef** [aharris88/phonegap-sms-plugin#42]
Hi there,
I've followed all steps, checked that sms.js and sms.java are located in the right directory, build the application without getting an error in the cmd. But when I'm trying to send a message, nothing happens, and none of the callback functions work.

My cordova version is 3.3.1

Here's my code:
```
           alert('sending sms');
            var number = "0123456789";
            var message = "test bericht"
            var intent = ""; //leave empty for sending sms using default intent
            var success = function () { alert('Message sent successfully'); };
            var error = function (e) { alert('Message Failed:' + e); };
            sms.send(number, message, intent, success, error);
```
I'm getting the sending sms alert, but nothing after that. I've also tried 
```
     var intent = "INTENT"; //leave empty for sending sms using default intent
```

when I emulate the app in ripple, this is what I get:
```
missing exec:Sms.send ripple.js:34331
Array[3] ripple.js:34332
TypeError ripple.js:34333
TypeError: Cannot read property 'send' of undefined
    at Object.module.exports.exec (http://localhost:4400/ripple/assets/ripple.js:34328:30)
    at Object.sms.send (http://localhost:4400/plugins/org.apache.cordova.plugin.sms/www/sms.js:5:13)
    at send (http://localhost:4400/js/app/newGroup.js:103:24)
    at HTMLButtonElement.onclick (http://localhost:4400/:116:121) ripple.js:34334
Sms ripple.js:50497
send 
```

What could be wrong here?
Thanks!

**Comment by aharris88** [comment]
Please see issue #53
